# coding: utf-8

"""
    Team 2 Pathfinding API

    Calculates minimum path between points depending on user generated map input.

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.obstacle import Obstacle


class TestObstacle(unittest.TestCase):
    """ Obstacle unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObstacle(self):
        """
        Test Obstacle
        """
        model = swagger_client.models.obstacle.Obstacle()


if __name__ == '__main__':
    unittest.main()
