# coding: utf-8

"""
    Team 2 Pathfinding API

    Calculates minimum path between points depending on user generated map input.

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.boundary_api import BoundaryApi


class TestBoundaryApi(unittest.TestCase):
    """ BoundaryApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.boundary_api.BoundaryApi()

    def tearDown(self):
        pass

    def test_get_boundary(self):
        """
        Test case for get_boundary

        Boundary
        """
        pass

    def test_update_boundary(self):
        """
        Test case for update_boundary

        Update the existing boundary value
        """
        pass


if __name__ == '__main__':
    unittest.main()
