# coding: utf-8

"""
    Team 2 Pathfinding API

    Calculates minimum path between points depending on user generated map input.

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.goal_api import GoalApi


class TestGoalApi(unittest.TestCase):
    """ GoalApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.goal_api.GoalApi()

    def tearDown(self):
        pass

    def test_get_goal(self):
        """
        Test case for get_goal

        Goal Location
        """
        pass

    def test_update_goal(self):
        """
        Test case for update_goal

        Update the existing goal value
        """
        pass


if __name__ == '__main__':
    unittest.main()
