# coding: utf-8

"""
    Team 2 Pathfinding API

    Calculates minimum path between points depending on user generated map input.

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.problems_api import ProblemsApi


class TestProblemsApi(unittest.TestCase):
    """ ProblemsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.problems_api.ProblemsApi()

    def tearDown(self):
        pass

    def test_add_problem(self):
        """
        Test case for add_problem

        Creates a new problem and returns a problemID
        """
        pass

    def test_delete_problem(self):
        """
        Test case for delete_problem

        Delete Problem
        """
        pass

    def test_get_problem(self):
        """
        Test case for get_problem

        Problems
        """
        pass


if __name__ == '__main__':
    unittest.main()
