# coding: utf-8

"""
    Team 2 Pathfinding API

    Calculates minimum path between points depending on user generated map input.

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.obstacles_api import ObstaclesApi


class TestObstaclesApi(unittest.TestCase):
    """ ObstaclesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.obstacles_api.ObstaclesApi()

    def tearDown(self):
        pass

    def test_add_obstacle(self):
        """
        Test case for add_obstacle

        Add a new obstacle to the list
        """
        pass

    def test_delete_obstacle(self):
        """
        Test case for delete_obstacle

        Delete Obstacle
        """
        pass

    def test_get_obstacle(self):
        """
        Test case for get_obstacle

        Obstacles
        """
        pass

    def test_get_obstacles(self):
        """
        Test case for get_obstacles

        Obstacles
        """
        pass

    def test_update_obstacle(self):
        """
        Test case for update_obstacle

        Update an existing obstacle
        """
        pass


if __name__ == '__main__':
    unittest.main()
