# coding: utf-8

"""
    Team 2 Pathfinding API

    Calculates minimum path between points depending on user generated map input.

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.robot_api import RobotApi


class TestRobotApi(unittest.TestCase):
    """ RobotApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.robot_api.RobotApi()

    def tearDown(self):
        pass

    def test_add_robot(self):
        """
        Test case for add_robot

        Add a new robot to the list
        """
        pass

    def test_delete_robot(self):
        """
        Test case for delete_robot

        Delete Robot
        """
        pass

    def test_get_robot(self):
        """
        Test case for get_robot

        Get a robot by the ID
        """
        pass

    def test_get_robots(self):
        """
        Test case for get_robots

        Robot
        """
        pass

    def test_update_robot(self):
        """
        Test case for update_robot

        Update the existing robot value
        """
        pass


if __name__ == '__main__':
    unittest.main()
