# coding: utf-8

"""
    Team 2 Pathfinding API

    Calculates minimum path between points depending on user generated map input.

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class ObstaclesApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def add_obstacle(self, problem_id, version, obstacle, **kwargs):
        """
        Add a new obstacle to the list
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.add_obstacle(problem_id, version, obstacle, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int problem_id: The id of the problem being manipulated (required)
        :param int version: The version of the obstacle to be updated. (required)
        :param Obstacle obstacle: Obstacle object that needs to be added to the list. (required)
        :return: int
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.add_obstacle_with_http_info(problem_id, version, obstacle, **kwargs)
        else:
            (data) = self.add_obstacle_with_http_info(problem_id, version, obstacle, **kwargs)
            return data

    def add_obstacle_with_http_info(self, problem_id, version, obstacle, **kwargs):
        """
        Add a new obstacle to the list
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.add_obstacle_with_http_info(problem_id, version, obstacle, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int problem_id: The id of the problem being manipulated (required)
        :param int version: The version of the obstacle to be updated. (required)
        :param Obstacle obstacle: Obstacle object that needs to be added to the list. (required)
        :return: int
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['problem_id', 'version', 'obstacle']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_obstacle" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'problem_id' is set
        if ('problem_id' not in params) or (params['problem_id'] is None):
            raise ValueError("Missing the required parameter `problem_id` when calling `add_obstacle`")
        # verify the required parameter 'version' is set
        if ('version' not in params) or (params['version'] is None):
            raise ValueError("Missing the required parameter `version` when calling `add_obstacle`")
        # verify the required parameter 'obstacle' is set
        if ('obstacle' not in params) or (params['obstacle'] is None):
            raise ValueError("Missing the required parameter `obstacle` when calling `add_obstacle`")


        collection_formats = {}

        resource_path = '/id&#x3D;{problem_id}/Obstacles/ver&#x3D;{version}/'.replace('{format}', 'json')
        path_params = {}
        if 'problem_id' in params:
            path_params['problem_id'] = params['problem_id']
        if 'version' in params:
            path_params['version'] = params['version']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'obstacle' in params:
            body_params = params['obstacle']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json', 'application/xml'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json', 'application/xml'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='int',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def delete_obstacle(self, problem_id, obstacle_id, version, **kwargs):
        """
        Delete Obstacle
        This removes the obstacle by the given ID
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.delete_obstacle(problem_id, obstacle_id, version, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int problem_id: The id of the problem being manipulated (required)
        :param int obstacle_id: The ID of the Obstacle that needs to be deleted. (required)
        :param int version: The version of the obstacle to be updated. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.delete_obstacle_with_http_info(problem_id, obstacle_id, version, **kwargs)
        else:
            (data) = self.delete_obstacle_with_http_info(problem_id, obstacle_id, version, **kwargs)
            return data

    def delete_obstacle_with_http_info(self, problem_id, obstacle_id, version, **kwargs):
        """
        Delete Obstacle
        This removes the obstacle by the given ID
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.delete_obstacle_with_http_info(problem_id, obstacle_id, version, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int problem_id: The id of the problem being manipulated (required)
        :param int obstacle_id: The ID of the Obstacle that needs to be deleted. (required)
        :param int version: The version of the obstacle to be updated. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['problem_id', 'obstacle_id', 'version']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_obstacle" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'problem_id' is set
        if ('problem_id' not in params) or (params['problem_id'] is None):
            raise ValueError("Missing the required parameter `problem_id` when calling `delete_obstacle`")
        # verify the required parameter 'obstacle_id' is set
        if ('obstacle_id' not in params) or (params['obstacle_id'] is None):
            raise ValueError("Missing the required parameter `obstacle_id` when calling `delete_obstacle`")
        # verify the required parameter 'version' is set
        if ('version' not in params) or (params['version'] is None):
            raise ValueError("Missing the required parameter `version` when calling `delete_obstacle`")


        collection_formats = {}

        resource_path = '/id&#x3D;{problem_id}/Obstacles/obstacle_id&#x3D;{obstacle_id}/ver&#x3D;{version}/'.replace('{format}', 'json')
        path_params = {}
        if 'problem_id' in params:
            path_params['problem_id'] = params['problem_id']
        if 'obstacle_id' in params:
            path_params['obstacle_id'] = params['obstacle_id']
        if 'version' in params:
            path_params['version'] = params['version']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json', 'application/xml'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_obstacle(self, problem_id, obstacle_id, **kwargs):
        """
        Obstacles
        Returns an obstacle 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_obstacle(problem_id, obstacle_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int problem_id: The id of the problem being manipulated (required)
        :param int obstacle_id: The id of the obstacle to be updated. (required)
        :return: Obstacle
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_obstacle_with_http_info(problem_id, obstacle_id, **kwargs)
        else:
            (data) = self.get_obstacle_with_http_info(problem_id, obstacle_id, **kwargs)
            return data

    def get_obstacle_with_http_info(self, problem_id, obstacle_id, **kwargs):
        """
        Obstacles
        Returns an obstacle 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_obstacle_with_http_info(problem_id, obstacle_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int problem_id: The id of the problem being manipulated (required)
        :param int obstacle_id: The id of the obstacle to be updated. (required)
        :return: Obstacle
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['problem_id', 'obstacle_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_obstacle" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'problem_id' is set
        if ('problem_id' not in params) or (params['problem_id'] is None):
            raise ValueError("Missing the required parameter `problem_id` when calling `get_obstacle`")
        # verify the required parameter 'obstacle_id' is set
        if ('obstacle_id' not in params) or (params['obstacle_id'] is None):
            raise ValueError("Missing the required parameter `obstacle_id` when calling `get_obstacle`")


        collection_formats = {}

        resource_path = '/id&#x3D;{problem_id}/Obstacles/obstacle_id&#x3D;{obstacle_id}'.replace('{format}', 'json')
        path_params = {}
        if 'problem_id' in params:
            path_params['problem_id'] = params['problem_id']
        if 'obstacle_id' in params:
            path_params['obstacle_id'] = params['obstacle_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json', 'application/xml'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='Obstacle',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_obstacles(self, problem_id, **kwargs):
        """
        Obstacles
        Returns a list of all of the obstacles in the problem. This can be an empty list. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_obstacles(problem_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int problem_id: The id of the problem being manipulated (required)
        :return: list[Obstacle]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_obstacles_with_http_info(problem_id, **kwargs)
        else:
            (data) = self.get_obstacles_with_http_info(problem_id, **kwargs)
            return data

    def get_obstacles_with_http_info(self, problem_id, **kwargs):
        """
        Obstacles
        Returns a list of all of the obstacles in the problem. This can be an empty list. 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_obstacles_with_http_info(problem_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int problem_id: The id of the problem being manipulated (required)
        :return: list[Obstacle]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['problem_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_obstacles" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'problem_id' is set
        if ('problem_id' not in params) or (params['problem_id'] is None):
            raise ValueError("Missing the required parameter `problem_id` when calling `get_obstacles`")


        collection_formats = {}

        resource_path = '/id&#x3D;{problem_id}/Obstacles'.replace('{format}', 'json')
        path_params = {}
        if 'problem_id' in params:
            path_params['problem_id'] = params['problem_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json', 'application/xml'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='list[Obstacle]',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def update_obstacle(self, problem_id, obstacle_id, version, **kwargs):
        """
        Update an existing obstacle
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.update_obstacle(problem_id, obstacle_id, version, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int problem_id: The id of the problem being manipulated (required)
        :param int obstacle_id: The id of the obstacle to be updated. (required)
        :param int version: The version of the obstacle to be updated. (required)
        :param Obstacle updated_obstacle: Obstacle object that needs to be added to the list.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.update_obstacle_with_http_info(problem_id, obstacle_id, version, **kwargs)
        else:
            (data) = self.update_obstacle_with_http_info(problem_id, obstacle_id, version, **kwargs)
            return data

    def update_obstacle_with_http_info(self, problem_id, obstacle_id, version, **kwargs):
        """
        Update an existing obstacle
        
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.update_obstacle_with_http_info(problem_id, obstacle_id, version, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int problem_id: The id of the problem being manipulated (required)
        :param int obstacle_id: The id of the obstacle to be updated. (required)
        :param int version: The version of the obstacle to be updated. (required)
        :param Obstacle updated_obstacle: Obstacle object that needs to be added to the list.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['problem_id', 'obstacle_id', 'version', 'updated_obstacle']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_obstacle" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'problem_id' is set
        if ('problem_id' not in params) or (params['problem_id'] is None):
            raise ValueError("Missing the required parameter `problem_id` when calling `update_obstacle`")
        # verify the required parameter 'obstacle_id' is set
        if ('obstacle_id' not in params) or (params['obstacle_id'] is None):
            raise ValueError("Missing the required parameter `obstacle_id` when calling `update_obstacle`")
        # verify the required parameter 'version' is set
        if ('version' not in params) or (params['version'] is None):
            raise ValueError("Missing the required parameter `version` when calling `update_obstacle`")


        collection_formats = {}

        resource_path = '/id&#x3D;{problem_id}/Obstacles/obstacle_id&#x3D;{obstacle_id}/ver&#x3D;{version}/'.replace('{format}', 'json')
        path_params = {}
        if 'problem_id' in params:
            path_params['problem_id'] = params['problem_id']
        if 'obstacle_id' in params:
            path_params['obstacle_id'] = params['obstacle_id']
        if 'version' in params:
            path_params['version'] = params['version']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'updated_obstacle' in params:
            body_params = params['updated_obstacle']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json', 'application/xml'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json', 'application/xml'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'PUT',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
