# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.shape import Shape
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Boundary(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, shape: str=None, boundary_info: Shape=None):
        """
        Boundary - a model defined in Swagger

        :param shape: The shape of this Boundary.
        :type shape: str
        :param boundary_info: The boundary_info of this Boundary.
        :type boundary_info: Shape
        """
        self.swagger_types = {
            'shape': str,
            'boundary_info': Shape
        }

        self.attribute_map = {
            'shape': 'shape',
            'boundary_info': 'boundaryInfo'
        }

        self._shape = shape
        self._boundary_info = boundary_info

    @classmethod
    def from_dict(cls, dikt) -> 'Boundary':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Boundary of this Boundary.
        :rtype: Boundary
        """
        return deserialize_model(dikt, cls)

    @property
    def shape(self) -> str:
        """
        Gets the shape of this Boundary.

        :return: The shape of this Boundary.
        :rtype: str
        """
        return self._shape

    @shape.setter
    def shape(self, shape: str):
        """
        Sets the shape of this Boundary.

        :param shape: The shape of this Boundary.
        :type shape: str
        """

        self._shape = shape

    @property
    def boundary_info(self) -> Shape:
        """
        Gets the boundary_info of this Boundary.

        :return: The boundary_info of this Boundary.
        :rtype: Shape
        """
        return self._boundary_info

    @boundary_info.setter
    def boundary_info(self, boundary_info: Shape):
        """
        Sets the boundary_info of this Boundary.

        :param boundary_info: The boundary_info of this Boundary.
        :type boundary_info: Shape
        """

        self._boundary_info = boundary_info

