# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.shape import Shape
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Obstacle(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, obstacle_id: int=None, shape: Shape=None):
        """
        Obstacle - a model defined in Swagger

        :param obstacle_id: The obstacle_id of this Obstacle.
        :type obstacle_id: int
        :param shape: The shape of this Obstacle.
        :type shape: Shape
        """
        self.swagger_types = {
            'obstacle_id': int,
            'shape': Shape
        }

        self.attribute_map = {
            'obstacle_id': 'obstacle_id',
            'shape': 'shape'
        }

        self._obstacle_id = obstacle_id
        self._shape = shape

    @classmethod
    def from_dict(cls, dikt) -> 'Obstacle':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Obstacle of this Obstacle.
        :rtype: Obstacle
        """
        return deserialize_model(dikt, cls)

    @property
    def obstacle_id(self) -> int:
        """
        Gets the obstacle_id of this Obstacle.
        Unique identifier representing a specific obstacle in the list.

        :return: The obstacle_id of this Obstacle.
        :rtype: int
        """
        return self._obstacle_id

    @obstacle_id.setter
    def obstacle_id(self, obstacle_id: int):
        """
        Sets the obstacle_id of this Obstacle.
        Unique identifier representing a specific obstacle in the list.

        :param obstacle_id: The obstacle_id of this Obstacle.
        :type obstacle_id: int
        """

        self._obstacle_id = obstacle_id

    @property
    def shape(self) -> Shape:
        """
        Gets the shape of this Obstacle.

        :return: The shape of this Obstacle.
        :rtype: Shape
        """
        return self._shape

    @shape.setter
    def shape(self, shape: Shape):
        """
        Sets the shape of this Obstacle.

        :param shape: The shape of this Obstacle.
        :type shape: Shape
        """

        self._shape = shape

