# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.coordinate import Coordinate
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Shape(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, shape_type: str='rectangle', coordinates: List[Coordinate]=None):
        """
        Shape - a model defined in Swagger

        :param name: The name of this Shape.
        :type name: str
        :param shape_type: The shape_type of this Shape.
        :type shape_type: str
        :param coordinates: The coordinates of this Shape.
        :type coordinates: List[Coordinate]
        """
        self.swagger_types = {
            'name': str,
            'shape_type': str,
            'coordinates': List[Coordinate]
        }

        self.attribute_map = {
            'name': 'name',
            'shape_type': 'shapeType',
            'coordinates': 'coordinates'
        }

        self._name = name
        self._shape_type = shape_type
        self._coordinates = coordinates

    @classmethod
    def from_dict(cls, dikt) -> 'Shape':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Shape of this Shape.
        :rtype: Shape
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this Shape.

        :return: The name of this Shape.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Shape.

        :param name: The name of this Shape.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def shape_type(self) -> str:
        """
        Gets the shape_type of this Shape.

        :return: The shape_type of this Shape.
        :rtype: str
        """
        return self._shape_type

    @shape_type.setter
    def shape_type(self, shape_type: str):
        """
        Sets the shape_type of this Shape.

        :param shape_type: The shape_type of this Shape.
        :type shape_type: str
        """
        allowed_values = ["rectangle", "triangle", "polygon"]
        if shape_type not in allowed_values:
            raise ValueError(
                "Invalid value for `shape_type` ({0}), must be one of {1}"
                .format(shape_type, allowed_values)
            )

        self._shape_type = shape_type

    @property
    def coordinates(self) -> List[Coordinate]:
        """
        Gets the coordinates of this Shape.

        :return: The coordinates of this Shape.
        :rtype: List[Coordinate]
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates: List[Coordinate]):
        """
        Sets the coordinates of this Shape.

        :param coordinates: The coordinates of this Shape.
        :type coordinates: List[Coordinate]
        """
        if coordinates is None:
            raise ValueError("Invalid value for `coordinates`, must not be `None`")

        self._coordinates = coordinates

