# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.coordinate import Coordinate
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class UnsearchedRegionPolygon(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: int=None, points: List[Coordinate]=None):
        """
        UnsearchedRegionPolygon - a model defined in Swagger

        :param id: The id of this UnsearchedRegionPolygon.
        :type id: int
        :param points: The points of this UnsearchedRegionPolygon.
        :type points: List[Coordinate]
        """
        self.swagger_types = {
            'id': int,
            'points': List[Coordinate]
        }

        self.attribute_map = {
            'id': 'id',
            'points': 'points'
        }

        self._id = id
        self._points = points

    @classmethod
    def from_dict(cls, dikt) -> 'UnsearchedRegionPolygon':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The unsearchedRegionPolygon of this UnsearchedRegionPolygon.
        :rtype: UnsearchedRegionPolygon
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """
        Gets the id of this UnsearchedRegionPolygon.

        :return: The id of this UnsearchedRegionPolygon.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """
        Sets the id of this UnsearchedRegionPolygon.

        :param id: The id of this UnsearchedRegionPolygon.
        :type id: int
        """
        if id is not None and id < 0:
            raise ValueError("Invalid value for `id`, must be a value greater than or equal to `0`")

        self._id = id

    @property
    def points(self) -> List[Coordinate]:
        """
        Gets the points of this UnsearchedRegionPolygon.

        :return: The points of this UnsearchedRegionPolygon.
        :rtype: List[Coordinate]
        """
        return self._points

    @points.setter
    def points(self, points: List[Coordinate]):
        """
        Sets the points of this UnsearchedRegionPolygon.

        :param points: The points of this UnsearchedRegionPolygon.
        :type points: List[Coordinate]
        """
        if points is None:
            raise ValueError("Invalid value for `points`, must not be `None`")

        self._points = points

