# coding: utf-8

"""
    Team 2 Pathfinding API

    Calculates minimum path between points depending on user generated map input.

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Boundary(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, boundary_info=None):
        """
        Boundary - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'boundary_info': 'list[Coordinate]'
        }

        self.attribute_map = {
            'boundary_info': 'boundary_info'
        }

        self._boundary_info = boundary_info

    @property
    def boundary_info(self):
        """
        Gets the boundary_info of this Boundary.

        :return: The boundary_info of this Boundary.
        :rtype: list[Coordinate]
        """
        return self._boundary_info

    @boundary_info.setter
    def boundary_info(self, boundary_info):
        """
        Sets the boundary_info of this Boundary.

        :param boundary_info: The boundary_info of this Boundary.
        :type: list[Coordinate]
        """

        self._boundary_info = boundary_info

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Boundary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
