# coding: utf-8

"""
    Team 2 Pathfinding API

    Calculates minimum path between points depending on user generated map input.

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Obstacle(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, obstacle_id=None, obstacle_info=None):
        """
        Obstacle - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'obstacle_id': 'int',
            'obstacle_info': 'list[Coordinate]'
        }

        self.attribute_map = {
            'obstacle_id': 'obstacle_id',
            'obstacle_info': 'obstacle_info'
        }

        self._obstacle_id = obstacle_id
        self._obstacle_info = obstacle_info

    @property
    def obstacle_id(self):
        """
        Gets the obstacle_id of this Obstacle.
        Unique identifier representing a specific obstacle in the list.

        :return: The obstacle_id of this Obstacle.
        :rtype: int
        """
        return self._obstacle_id

    @obstacle_id.setter
    def obstacle_id(self, obstacle_id):
        """
        Sets the obstacle_id of this Obstacle.
        Unique identifier representing a specific obstacle in the list.

        :param obstacle_id: The obstacle_id of this Obstacle.
        :type: int
        """

        self._obstacle_id = obstacle_id

    @property
    def obstacle_info(self):
        """
        Gets the obstacle_info of this Obstacle.

        :return: The obstacle_info of this Obstacle.
        :rtype: list[Coordinate]
        """
        return self._obstacle_info

    @obstacle_info.setter
    def obstacle_info(self, obstacle_info):
        """
        Sets the obstacle_info of this Obstacle.

        :param obstacle_info: The obstacle_info of this Obstacle.
        :type: list[Coordinate]
        """

        self._obstacle_info = obstacle_info

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Obstacle):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
