# coding: utf-8

"""
    Team 2 Pathfinding API

    Calculates minimum path between points depending on user generated map input.

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Path(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, path_cost=None, coordinates=None):
        """
        Path - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'path_cost': 'float',
            'coordinates': 'list[Coordinate]'
        }

        self.attribute_map = {
            'path_cost': 'path_cost',
            'coordinates': 'coordinates'
        }

        self._path_cost = path_cost
        self._coordinates = coordinates

    @property
    def path_cost(self):
        """
        Gets the path_cost of this Path.
        The total cost to travel the path

        :return: The path_cost of this Path.
        :rtype: float
        """
        return self._path_cost

    @path_cost.setter
    def path_cost(self, path_cost):
        """
        Sets the path_cost of this Path.
        The total cost to travel the path

        :param path_cost: The path_cost of this Path.
        :type: float
        """

        self._path_cost = path_cost

    @property
    def coordinates(self):
        """
        Gets the coordinates of this Path.
        The path travelled

        :return: The coordinates of this Path.
        :rtype: list[Coordinate]
        """
        return self._coordinates

    @coordinates.setter
    def coordinates(self, coordinates):
        """
        Sets the coordinates of this Path.
        The path travelled

        :param coordinates: The coordinates of this Path.
        :type: list[Coordinate]
        """

        self._coordinates = coordinates

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Path):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
